version: "3.9"

services:
  app:
    build: ./api
    entrypoint: ["uvicorn", "app:app", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/app

networks:
  nginx:
    external: true